package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ConfList generated by hbm2java
 */
@Entity
@Table(name = "conf_list", catalog = "crawler")
public class ConfList implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
	private String url;
	private Section section;
	private String comment;
	private String category;
	private Byte auth;
	private Byte ajax;
	private Integer numThreads;
	private Integer fetchinterval;
	private String filterurl;
	private String listdom;
	private String linedom;
	private String urldom;
	private String datedom;
	private String updatedom;
	private String synopsisdom;

	private Set<ConfDetail> confDetails = new HashSet<ConfDetail>(0);

	public ConfList() {
	}

	public ConfList(Section section) {
		this.section = section;
	}

	public ConfList(Section section, String comment, String category, Byte auth, Byte ajax,
	        Integer numThreads, Integer fetchinterval, String filterurl, String listdom,
	        String linedom, String urldom, String datedom, String updatedom, String synopsisdom,
	        Set<ConfDetail> confDetails) {
		this.section = section;
		this.comment = comment;
		this.category = category;
		this.auth = auth;
		this.ajax = ajax;
		this.numThreads = numThreads;
		this.fetchinterval = fetchinterval;
		this.filterurl = filterurl;
		this.listdom = listdom;
		this.linedom = linedom;
		this.urldom = urldom;
		this.datedom = datedom;
		this.updatedom = updatedom;
		this.synopsisdom = synopsisdom;
		this.confDetails = confDetails;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "section"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "url", unique = true, nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "comment", length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "auth")
	public Byte getAuth() {
		return this.auth;
	}

	public void setAuth(Byte auth) {
		this.auth = auth;
	}

	@Column(name = "ajax")
	public Byte getAjax() {
		return this.ajax;
	}

	public void setAjax(Byte ajax) {
		this.ajax = ajax;
	}

	@Column(name = "numThreads")
	public Integer getNumThreads() {
		return this.numThreads;
	}

	public void setNumThreads(Integer numThreads) {
		this.numThreads = numThreads;
	}

	@Column(name = "fetchinterval")
	public Integer getFetchinterval() {
		return this.fetchinterval;
	}

	public void setFetchinterval(Integer fetchinterval) {
		this.fetchinterval = fetchinterval;
	}

	@Column(name = "filterurl", length = 300)
	public String getFilterurl() {
		return this.filterurl;
	}

	public void setFilterurl(String filterurl) {
		this.filterurl = filterurl;
	}

	@Column(name = "listdom", length = 300)
	public String getListdom() {
		return this.listdom;
	}

	public void setListdom(String listdom) {
		this.listdom = listdom;
	}

	@Column(name = "linedom", length = 300)
	public String getLinedom() {
		return this.linedom;
	}

	public void setLinedom(String linedom) {
		this.linedom = linedom;
	}

	@Column(name = "urldom", length = 100)
	public String getUrldom() {
		return this.urldom;
	}

	public void setUrldom(String urldom) {
		this.urldom = urldom;
	}

	@Column(name = "datedom", length = 100)
	public String getDatedom() {
		return this.datedom;
	}

	public void setDatedom(String datedom) {
		this.datedom = datedom;
	}

	@Column(name = "updatedom", length = 100)
	public String getUpdatedom() {
		return this.updatedom;
	}

	public void setUpdatedom(String updatedom) {
		this.updatedom = updatedom;
	}

	@Column(name = "synopsisdom", length = 100)
	public String getSynopsisdom() {
		return this.synopsisdom;
	}

	public void setSynopsisdom(String synopsisdom) {
		this.synopsisdom = synopsisdom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "confList")
	public Set<ConfDetail> getConfDetails() {
		return this.confDetails;
	}

	public void setConfDetails(Set<ConfDetail> confDetails) {
		this.confDetails = confDetails;
	}

}
