package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConfDetailId generated by hbm2java
 */
@Embeddable
public class ConfDetailId implements java.io.Serializable {

	private String listurl;
	private String host;

	public ConfDetailId() {
	}

	public ConfDetailId(String listurl, String host) {
		this.listurl = listurl;
		this.host = host;
	}

	@Column(name = "listurl", nullable = false, length = 150)
	public String getListurl() {
		return this.listurl;
	}

	public void setListurl(String listurl) {
		this.listurl = listurl;
	}

	@Column(name = "host", nullable = false, length = 150)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfDetailId))
			return false;
		ConfDetailId castOther = (ConfDetailId) other;

		return ((this.getListurl() == castOther.getListurl()) || (this.getListurl() != null
		        && castOther.getListurl() != null && this.getListurl().equals(
		        castOther.getListurl())))
		        && ((this.getHost() == castOther.getHost()) || (this.getHost() != null
		                && castOther.getHost() != null && this.getHost()
		                .equals(castOther.getHost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getListurl() == null ? 0 : this.getListurl().hashCode());
		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		return result;
	}

}
