package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "crawler")
public class Location implements java.io.Serializable {

        /**
         * 
         */
        private static final long serialVersionUID = -2135529805502065005L;
        private Integer id;
        private String name;
        private Integer pid;
        private Float longitude;
        private Float latitude;
        private Integer pot;

        public Location() {
        }

        public Location(Integer id, String name, Integer pid, Float longitude, Float latitude, Integer pot) {
                super();
                this.id = id;
                this.name = name;
                this.pid = pid;
                this.longitude = longitude;
                this.latitude = latitude;
                this.pot = pot;
        }

        @Id
        @Column(name = "id", unique = true, nullable = false)
        public Integer getId() {
                return this.id;
        }

        public void setId(Integer id) {
                this.id = id;
        }

        @Column(name = "name", nullable = false, length = 60)
        public String getName() {
                return name;
        }

        public void setName(String name) {
                this.name = name;
        }

        @Column(name = "pid")
        public Integer getPid() {
                return pid;
        }

        public void setPid(Integer pid) {
                this.pid = pid;
        }

        @Column(name = "longitude")
        public Float getLongitude() {
                return longitude;
        }

        public void setLongitude(Float longitude) {
                this.longitude = longitude;
        }

        @Column(name = "latitude")
        public Float getLatitude() {
                return latitude;
        }

        public void setLatitude(Float latitude) {
                this.latitude = latitude;
        }

        @Column(name = "pot")
        public Integer getPot() {
                return pot;
        }

        public void setPot(int pot) {
                this.pot = pot;
        }

}
