package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Machine generated by hbm2java
 */
@Entity
@Table(name = "machine", catalog = "crawler")
public class Machine implements java.io.Serializable {

	private String ip;
	private Integer port;
	private String comment;

	public Machine() {
	}

	public Machine(String ip) {
		this.ip = ip;
	}

	public Machine(String ip, Integer port, String comment) {
		this.ip = ip;
		this.port = port;
		this.comment = comment;
	}

	@Id
	@Column(name = "ip", unique = true, nullable = false, length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "comment", length = 100)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
