package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProxyId generated by hbm2java
 */
@Embeddable
public class ProxyId implements java.io.Serializable {

	private String ip;
	private int port;

	public ProxyId() {
	}

	public ProxyId(String ip, int port) {
		this.ip = ip;
		this.port = port;
	}

	@Column(name = "ip", nullable = false, length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProxyId))
			return false;
		ProxyId castOther = (ProxyId) other;

		return ((this.getIp() == castOther.getIp()) || (this.getIp() != null
		        && castOther.getIp() != null && this.getIp().equals(castOther.getIp())))
		        && (this.getPort() == castOther.getPort());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		result = 37 * result + this.getPort();
		return result;
	}

}
