package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proxy generated by hbm2java
 */
@Entity
@Table(name = "proxy", catalog = "crawler")
public class Proxy implements java.io.Serializable {

	private ProxyId id;
	private SiteType siteType;

	public Proxy() {
	}

	public Proxy(ProxyId id) {
		this.id = id;
	}

	public Proxy(ProxyId id, SiteType siteType) {
		this.id = id;
		this.siteType = siteType;
	}

	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "ip", column = @Column(name = "ip", nullable = false, length = 45)),
	        @AttributeOverride(name = "port", column = @Column(name = "port", nullable = false)) })
	public ProxyId getId() {
		return this.id;
	}

	public void setId(ProxyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type")
	public SiteType getSiteType() {
		return this.siteType;
	}

	public void setSiteType(SiteType siteType) {
		this.siteType = siteType;
	}

}
