package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SearchEngine generated by hbm2java
 */
@Entity
@Table(name = "search_engine", catalog = "crawler")
public class SearchEngine implements java.io.Serializable {

	/**
	 * 
	 */
    private static final long serialVersionUID = 610993177567328192L;
	private String id;
	private String url;

	public SearchEngine() {
	}

	public SearchEngine(String id) {
		this.id = id;
	}

	public SearchEngine(String id, String url) {
		this.id = id;
		this.url = url;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
