package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "crawler")
public class Section implements java.io.Serializable {

	private String url;
	private String category;
	private String comment;
	private String urlbase64;
	private Website website;
	private ConfList confList;

	public Section() {
	}

	public Section(String url, String urlbase64) {
		this.url = url;
		this.urlbase64 = urlbase64;
	}

	public Section(String url, Website website, ConfList confList) {
		this.url = url;
		this.website = website;
		this.confList = confList;
	}

	@Id
	@Column(name = "url", unique = true, nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name="category", nullable = false, length = 45)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name="comment", nullable = false, length = 45)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name="urlbase64", nullable = false, length=150)
	public String getUrlbase64() {
		return urlbase64;
	}

	public void setUrlbase64(String urlbase64) {
		this.urlbase64 = urlbase64;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site")
	public Website getWebsite() {
		return this.website;
	}

	public void setWebsite(Website website) {
		this.website = website;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "section")
	public ConfList getConfList() {
		return this.confList;
	}

	public void setConfList(ConfList confList) {
		this.confList = confList;
	}

}
