package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "crawler")
public class Section implements java.io.Serializable {

	/**
	 * 
	 */
    private static final long serialVersionUID = -7399722190855313390L;
	private String url;
	private Website website;
	private Account account;
	private String category;
	private String comment;
	private String urlbase64;
	private String status;

	public Section() {
	}

	public Section(String url, String category, String comment, String urlbase64) {
		this.url = url;
		this.category = category;
		this.comment = comment;
		this.urlbase64 = urlbase64;
	}

	public Section(String url, Website website, Account account, String category, String comment,
	        String urlbase64, String status) {
		this.url = url;
		this.website = website;
		this.account = account;
		this.category = category;
		this.comment = comment;
		this.urlbase64 = urlbase64;
		this.status = status;
	}

	public Section(String url, String urlbase64) {
	    this.url = url;
	    this.urlbase64 = urlbase64;
    }

	@Id
	@Column(name = "url", unique = true, nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site")
	public Website getWebsite() {
		return this.website;
	}

	public void setWebsite(Website website) {
		this.website = website;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "comment", nullable = false, length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "urlbase64", nullable = false, length = 150)
	public String getUrlbase64() {
		return this.urlbase64;
	}

	public void setUrlbase64(String urlbase64) {
		this.urlbase64 = urlbase64;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
