package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "crawler")
public class Section implements java.io.Serializable {

	/**
	 * 
	 */
    private static final long serialVersionUID = -7399722190855313390L;
    private String id;
	private String url;
	private Website website;
	private Account account;
	private Category category;
	private String comment;
	private String status;
	
//	private ConfList confList;

	public Section() {
	}

	public Section(String url, String comment) {
		this.url = url;
		this.comment = comment;
	}

	public Section(String url, Website website, Account account, Category category, String comment,
	       String status) {
		this.url = url;
		this.website = website;
		this.account = account;
		this.category = category;
		this.comment = comment;
		this.status = status;
	}

	public Section(String url) {
	    this.url = url;
    }

	@Id
	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 150)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "url", unique = true, nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site")
	public Website getWebsite() {
		return this.website;
	}

	public void setWebsite(Website website) {
		this.website = website;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "comment", nullable = false, length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}


	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

//	@OneToOne(fetch = FetchType.LAZY,mappedBy = "url")
//	public ConfList getConfList() {
//		return confList;
//	}
//
//	public void setConfList(ConfList confList) {
//		this.confList = confList;
//	}

	
}
