package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiteType generated by hbm2java
 */
@Entity
@Table(name = "site_type", catalog = "crawler")
public class SiteType implements java.io.Serializable {

    private static final long serialVersionUID = 9139932773606914700L;
    
	private String type;
	private String comment;
	private Set<Proxy> proxies = new HashSet<Proxy>(0);
	private Set<Website> websites = new HashSet<Website>(0);

	public SiteType() {
	}

	public SiteType(String type) {
		this.type = type;
	}

	public SiteType(String type, String comment, Set<Proxy> proxies, Set<Website> websites) {
		this.type = type;
		this.comment = comment;
		this.proxies = proxies;
		this.websites = websites;
	}

	@Id
	@Column(name = "type", unique = true, nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "comment", length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siteType")
	public Set<Proxy> getProxies() {
		return this.proxies;
	}

	public void setProxies(Set<Proxy> proxies) {
		this.proxies = proxies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siteType")
	public Set<Website> getWebsites() {
		return this.websites;
	}

	public void setWebsites(Set<Website> websites) {
		this.websites = websites;
	}

}
