package com.zxsoft.crawler.entity;

// Generated 2014-9-19 17:19:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Website generated by hbm2java
 */
@Entity
@Table(name = "website", catalog = "crawler")
public class Website implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5354652608097154552L;
	private String id;
	private String site;
	private SiteType siteType;
	private String username;
	private String password;
	private String comment;
	private String region;
	private String status;
	private Set<Section> sections = new HashSet<Section>(0);

	public Website() {
	}

	public Website(String site, SiteType siteType, String comment) {
		this.site = site;
		this.siteType = siteType;
		this.comment = comment;
	}

	public Website(String site, SiteType siteType, String username, String password,
	        String comment, String region, Set<Section> sections) {
		this.site = site;
		this.siteType = siteType;
		this.username = username;
		this.password = password;
		this.comment = comment;
		this.region = region;
		this.sections = sections;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 150)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "site", unique = true, nullable = false, length = 150)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public SiteType getSiteType() {
		return this.siteType;
	}

	public void setSiteType(SiteType siteType) {
		this.siteType = siteType;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "comment", nullable = false, length = 100)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "region", length = 45)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name="status", length = 45)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "website")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}

}
