package com.zxsoft.crawler.entity;

// Generated 2014-9-15 17:18:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Website generated by hbm2java
 */
@Entity
@Table(name = "website", catalog = "crawler")
public class Website implements java.io.Serializable {

	private String site;
	private SiteType siteType;
	private String username;
	private String password;
	private String comment;
	private String sitebase64;
	private String region;
	private Set<Section> sections = new HashSet<Section>(0);

	public Website() {
	}

	public Website(String site, String comment, SiteType siteType) {
		this.site = site;
		this.comment = comment;
		this.siteType = siteType;
	}

	public Website(String site, SiteType siteType, String username, String password, Set<Section> sections) {
		this.site = site;
		this.siteType = siteType;
		this.username = username;
		this.password = password;
		this.sections = sections;
	}

	@Id
	@Column(name = "site", unique = true, nullable = false, length = 150)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public SiteType getSiteType() {
		return this.siteType;
	}

	public void setSiteType(SiteType siteType) {
		this.siteType = siteType;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "comment", length = 100, nullable = false)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name="sitebase64", length= 150, nullable = false)
	public String getSitebase64() {
		return sitebase64;
	}

	public void setSitebase64(String sitebase64) {
		this.sitebase64 = sitebase64;
	}
	
	@Column(name = "region", length = 45)
	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "website")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}

}
