// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.zxsoft.crawler.common;

import com.zxsoft.crawler.api.JobType;
import com.zxsoft.crawler.common.JobConf.State;
import java.util.HashSet;
import java.util.Set;

public class JobConfBuilder extends JobConfBuilderBase<JobConfBuilder> {
    public static JobConfBuilder jobConf() {
        return new JobConfBuilder();
    }

    public JobConfBuilder() {
        super(new JobConf());
    }

    public JobConf build() {
        return getInstance();
    }
}

class JobConfBuilderBase<GeneratorT extends JobConfBuilderBase<GeneratorT>> {
    private JobConf instance;

    protected JobConfBuilderBase(JobConf aInstance) {
        instance = aInstance;
    }

    protected JobConf getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withJobType(JobType aValue) {
        instance.setJobType(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUrl(String aValue) {
        instance.setUrl(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withWorkerId(int aValue) {
        instance.setWorkerId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withKeyword(String aValue) {
        instance.setKeyword(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withKeywordEncode(String aValue) {
        instance.setKeywordEncode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAutoUrl(boolean aValue) {
        instance.setAutoUrl(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withEncode(String aValue) {
        instance.setEncode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSource_name(String aValue) {
        instance.setSource_name(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPlatform(int aValue) {
        instance.setPlatform(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSource_id(int aValue) {
        instance.setSource_id(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withJobId(int aValue) {
        instance.setJobId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withIp(String aValue) {
        instance.setIp(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCountry_code(int aValue) {
        instance.setCountry_code(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withProvince_code(int aValue) {
        instance.setProvince_code(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCity_code(int aValue) {
        instance.setCity_code(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withState(State aValue) {
        instance.setState(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPrevFetchTime(long aValue) {
        instance.setPrevFetchTime(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSectionId(int aValue) {
        instance.setSectionId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withType(String aValue) {
        instance.setType(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withFetchinterval(int aValue) {
        instance.setFetchinterval(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withStart(long aValue) {
        instance.setStart(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCount(int aValue) {
        instance.setCount(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUsername(String aValue) {
        instance.setUsername(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPassword(String aValue) {
        instance.setPassword(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAuth(Boolean aValue) {
        instance.setAuth(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withListRule(ListRule aValue) {
        instance.setListRule(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDetailRules(Set<DetailRule> aValue) {
        instance.setDetailRules(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAddedDetailRule(DetailRule aValue) {
        if (instance.getDetailRules() == null) {
            instance.setDetailRules(new HashSet<DetailRule>());
        }

        ((HashSet<DetailRule>) instance.getDetailRules()).add(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLocation(String aValue) {
        instance.setLocation(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLocationCode(int aValue) {
        instance.setLocationCode(aValue);

        return (GeneratorT) this;
    }
}
